version: '3.8'

services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
