module.exports = {
  signupValidationError: 'Error registering user',
  loginValidationError: 'Error logging in',
  badCredentials: 'Bad credentials',
  verifyEmailValidationError: 'Email verification failed',
  userNotFound: 'User not found',
  userIdRequired: 'User ID required',
  tokenInvalid: 'Token invalid',
  tokenRequired: 'Token is required',
  tokenValidation: 'Token invalid',
  userExists: 'User already exists',
  emailRequired: 'Email should be non empty string',
  resetPasswordValidationError: 'Reset password validation error',
  userNotAuthorized: 'User is not authorized to perform the action',
  firstNameValidation: 'First name should be non empty string',
  lastNameValidation: 'Last name should be non empty string',
  passwordValidation: 'Password should be non empty string',
  userNotAuthenticated: 'User is not authenticated',
  notImplemented: 'Not implemented',
  resourceConflict: 'Resource conflict',
  internalServerError: 'Internal server error',
  validationError: 'Validation error',
  emailVerifiedInputValidation: 'Email verification input validation error',
  idRequired: 'ID is requried',
  forbidden: 'Forbidden',
  resourceNotFound: 'Resource not found',
  invalidEmail: 'Email is invalid',
  registerSuccess: 'Registered successfully',
  loginSuccess: 'Logged in successfully',
  verifyEmailSuccess: 'Email verified. You can now login',
  forgotPasswordSuccess: 'Please check your email to reset your password',
  resetPasswordSuccess: 'Reset password successfully',
  resendEmailVerificationSuccess: 'Email has been sent.',
  logoutSuccess: 'Logout successfull',
  userListedSuccess: 'User listed',
  userUpdateSuccess: 'User updated',
  userCreateSuccess: 'User created',
  userDeleteSuccess: 'User deleted',
  cannotDeleteOwnAccount: 'User cannot delete own account',
  roleValidation: 'Role must be non empty string',
  passwordNotMatch: 'Password does not match.',
  changePasswordSuccessful: 'Password changed.',
};
